### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Raingate** [TravisL24/HECKTOR#1]
Hi Travis !

I'm currently tryin to reproduce some of the works on HECKTOR 2020's leaderboard,
but can't find the dataset.

Could you kindly share the official dataset ?
Thanks !

**Comment by TravisL24** [comment]
Sorry, I don't have permission to the 2020 dataset.&nbsp;My experiments were based on the HECKTOR 2021 dataset supplemented by HECKTOR 2020.&nbsp;


I do not have the right to privately distribute specific datasets due to signing the sponsor's EUA document.


You can get the dataset on https://www.aicrowd.com/challenges/miccai-2021-hecktor.


But I may have some helpful documents for you here, you can leave your private email for easy communication.


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "TravisL24/HECKTOR"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Mar 20, 2022 05:15 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[TravisL24/HECKTOR] About dataset (Issue #1)





 
Hi Travis !
 
I'm currently tryin to reproduce some of the works on HECKTOR 2020's leaderboard,
 but can't find the dataset.
 
Could you kindly share the official dataset ?
 Thanks !
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
